mod analyze;

use std::path::PathBuf;

use analyze::{analyze_run, render_text};
use clap::{Parser, ValueEnum};
use tailscope_core::Run;

#[derive(Debug, Parser)]
#[command(name = "tailscope")]
#[command(about = "Analyze tailscope run artifacts", version)]
struct Cli {
    #[command(subcommand)]
    command: Command,
}

#[derive(Debug, clap::Subcommand)]
enum Command {
    /// Analyze one tailscope run JSON artifact.
    Analyze {
        /// Path to a run JSON file generated by tailscope-core.
        #[arg(value_name = "RUN_JSON")]
        run_json: PathBuf,
        /// Output format for the diagnosis report.
        #[arg(long, value_enum, default_value_t = OutputFormat::Text)]
        format: OutputFormat,
    },
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, ValueEnum)]
enum OutputFormat {
    Text,
    Json,
}

fn main() -> Result<(), Box<dyn std::error::Error>> {
    let cli = Cli::parse();

    match cli.command {
        Command::Analyze { run_json, format } => {
            let input = std::fs::read_to_string(&run_json)?;
            let run: Run = serde_json::from_str(&input)?;
            let report = analyze_run(&run);

            match format {
                OutputFormat::Text => {
                    println!("{}", render_text(&report));
                }
                OutputFormat::Json => {
                    println!("{}", serde_json::to_string_pretty(&report)?);
                }
            }
        }
    }

    Ok(())
}
