use std::fmt::Write as _;
use std::path::PathBuf;

use clap::{Parser, ValueEnum};
use tailtriage_analyzer::{render_json_pretty, render_text, try_analyze_run};
use tailtriage_cli::artifact::{decode_run_artifact, ArtifactLoadError};
use tailtriage_cli::{analyzer_options_help_text, build_analyze_options};
use tailtriage_core::{
    validate_run_strict, CaptureLimitsOverride, CaptureMode, LocalJsonSink, RunSink,
    RunValidationSeverity,
};
use tailtriage_tracing::{ensure_persistable_run_has_requests, import_jsonl_path, ImportOptions};

#[derive(Debug, Parser)]
#[command(name = "tailtriage")]
#[command(about = "Import and analyze tailtriage run artifacts", version)]
struct Cli {
    #[command(subcommand)]
    command: Command,
}

#[derive(Debug, clap::Subcommand)]
enum Command {
    /// Import completed tailtriage tracing span JSONL into a Run JSON artifact.
    Import {
        #[command(subcommand)]
        command: ImportCommand,
    },
    /// Analyze one tailtriage run JSON artifact.
    Analyze {
        /// Path to a run JSON file generated by tailtriage-core.
        #[arg(value_name = "RUN_JSON")]
        run_json: Option<PathBuf>,
        /// Output format for the diagnosis report.
        #[arg(long, value_enum, default_value_t = OutputFormat::Text)]
        format: OutputFormat,
        /// Path to analyzer TOML config. Applied before `--analyzer-set` overrides.
        #[arg(long, value_name = "TOML")]
        analyzer_config: Option<PathBuf>,
        /// Analyzer override in `path=value` form; may be repeated.
        #[arg(long = "analyzer-set", value_name = "PATH=VALUE")]
        analyzer_set: Vec<String>,
        /// Print analyzer option help and exit successfully.
        #[arg(long)]
        help_analyzer_options: bool,
        /// Fail when request-scoped artifact invariants are ambiguous.
        #[arg(long)]
        strict_artifact: bool,
    },
}

#[derive(Debug, clap::Subcommand)]
enum ImportCommand {
    /// Import completed `tt.*` tailtriage tracing span JSONL into Run JSON.
    #[command(name = "tracing-spans-jsonl")]
    TracingSpansJsonl {
        /// Path to completed tailtriage tracing span JSONL records.
        #[arg(value_name = "SPANS_JSONL")]
        spans_jsonl: PathBuf,
        /// Service name to store in imported run metadata.
        #[arg(long, value_name = "SERVICE")]
        service: String,
        /// Path where imported run JSON should be written.
        #[arg(long, value_name = "RUN_JSON")]
        output: PathBuf,
        /// Optional service version to store in run metadata.
        #[arg(long, value_name = "VERSION")]
        service_version: Option<String>,
        /// Optional explicit run id for imported run metadata.
        #[arg(long, value_name = "RUN_ID")]
        run_id: Option<String>,
        /// Fail on malformed/incomplete tailtriage spans.
        #[arg(long)]
        strict: bool,
        /// Import capture mode semantics for request/stage/queue retention.
        #[arg(long, value_enum, default_value_t = ImportCaptureMode::Light)]
        mode: ImportCaptureMode,
        /// Override max retained request events for imported evidence.
        #[arg(long)]
        max_requests: Option<usize>,
        /// Override max retained stage events for imported evidence.
        #[arg(long)]
        max_stages: Option<usize>,
        /// Override max retained queue events for imported evidence.
        #[arg(long)]
        max_queues: Option<usize>,
    },
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, ValueEnum)]
enum ImportCaptureMode {
    Light,
    Investigation,
}

impl From<ImportCaptureMode> for CaptureMode {
    fn from(value: ImportCaptureMode) -> Self {
        match value {
            ImportCaptureMode::Light => Self::Light,
            ImportCaptureMode::Investigation => Self::Investigation,
        }
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, ValueEnum)]
enum OutputFormat {
    Text,
    Json,
}

fn run() -> Result<(), Box<dyn std::error::Error>> {
    let cli = Cli::parse();

    match cli.command {
        Command::Import { command } => match command {
            ImportCommand::TracingSpansJsonl {
                spans_jsonl,
                service,
                output,
                service_version,
                run_id,
                strict,
                mode,
                max_requests,
                max_stages,
                max_queues,
            } => import_tracing_spans_jsonl(
                spans_jsonl,
                service,
                &output,
                service_version,
                run_id,
                strict,
                mode,
                max_requests,
                max_stages,
                max_queues,
            )?,
        },
        Command::Analyze {
            run_json,
            format,
            analyzer_config,
            analyzer_set,
            help_analyzer_options,
            strict_artifact,
        } => {
            if help_analyzer_options {
                println!("{}", analyzer_options_help_text());
                return Ok(());
            }

            let run_json = run_json.ok_or_else(|| {
                clap::Error::raw(
                    clap::error::ErrorKind::MissingRequiredArgument,
                    "missing required RUN_JSON argument (or use --help-analyzer-options)",
                )
            })?;
            let loaded = decode_run_artifact(&run_json)?;
            if strict_artifact {
                validate_cli_strict_artifact(&loaded.original_run)?;
            }
            if loaded.run.requests.is_empty() {
                return Err(ArtifactLoadError::Validation {
                    path: run_json.clone(),
                    message: "requests section is empty. Capture at least one request event before running triage.".to_string(),
                }
                .into());
            }
            for warning in &loaded.warnings {
                eprintln!("warning: {warning}");
            }
            let options = build_analyze_options(analyzer_config.as_deref(), &analyzer_set)?;
            let report = try_analyze_run(&loaded.original_run, options)?;

            match format {
                OutputFormat::Text => {
                    println!("{}", render_text(&report));
                }
                OutputFormat::Json => {
                    println!("{}", render_json_pretty(&report)?);
                }
            }
        }
    }

    Ok(())
}

fn validate_cli_strict_artifact(run: &tailtriage_core::Run) -> Result<(), std::io::Error> {
    validate_run_strict(run).map_err(|err| {
        let mut codes = err
            .report()
            .issues
            .iter()
            .filter(|issue| issue.severity == RunValidationSeverity::Error)
            .map(|issue| issue.code.as_str())
            .collect::<Vec<_>>();
        codes.sort_unstable();
        codes.dedup();

        let error_count = err
            .report()
            .issues
            .iter()
            .filter(|issue| issue.severity == RunValidationSeverity::Error)
            .count();
        let detail_limit = 8;
        let mut details = err
            .report()
            .issues
            .iter()
            .filter(|issue| issue.severity == RunValidationSeverity::Error)
            .take(detail_limit)
            .map(|issue| {
                let mut location = issue.location.section.as_str().to_string();
                if let Some(index) = issue.location.index {
                    write!(location, "[{index}]").expect("writing to String should not fail");
                }
                if let Some(field) = issue.location.field {
                    location.push('.');
                    location.push_str(field);
                }
                format!("{} at {location}: {}", issue.code.as_str(), issue.message)
            })
            .collect::<Vec<_>>();
        if error_count > detail_limit {
            details.push(format!(
                "{} additional error finding(s) omitted",
                error_count - detail_limit
            ));
        }
        if details.is_empty() {
            details.push(err.to_string());
        }
        std::io::Error::new(
            std::io::ErrorKind::InvalidData,
            format!(
                "strict artifact validation failed; core issue code(s): {}; {}",
                codes.join(", "),
                details.join("; ")
            ),
        )
    })
}

fn create_output_parent_dir(path: &std::path::Path) -> Result<(), std::io::Error> {
    let Some(parent) = path.parent() else {
        return Ok(());
    };
    if parent.as_os_str().is_empty() {
        return Ok(());
    }
    std::fs::create_dir_all(parent).map_err(|err| {
        std::io::Error::new(
            err.kind(),
            format!(
                "failed to create output parent directory '{}': {err}",
                parent.display()
            ),
        )
    })
}

#[allow(clippy::too_many_arguments)]
fn import_tracing_spans_jsonl(
    spans_jsonl: PathBuf,
    service: String,
    output: &PathBuf,
    service_version: Option<String>,
    run_id: Option<String>,
    strict: bool,
    mode: ImportCaptureMode,
    max_requests: Option<usize>,
    max_stages: Option<usize>,
    max_queues: Option<usize>,
) -> Result<(), Box<dyn std::error::Error>> {
    if max_requests == Some(0) {
        return Err(std::io::Error::new(
            std::io::ErrorKind::InvalidInput,
            "--max-requests must be at least 1 for persisted tracing import; tailtriage analyze requires at least one request event",
        )
        .into());
    }

    let mut options = ImportOptions::new(service).strict(strict).mode(mode.into());
    if let Some(service_version) = service_version {
        options = options.service_version(service_version);
    }
    if let Some(run_id) = run_id {
        options = options.run_id(run_id);
    }
    let mut capture_limits_override = CaptureLimitsOverride::default();
    if let Some(max_requests) = max_requests {
        capture_limits_override.max_requests = Some(max_requests);
    }
    if let Some(max_stages) = max_stages {
        capture_limits_override.max_stages = Some(max_stages);
    }
    if let Some(max_queues) = max_queues {
        capture_limits_override.max_queues = Some(max_queues);
    }
    options = options.capture_limits_override(capture_limits_override);

    let imported = import_jsonl_path(spans_jsonl, options).map_err(|err| {
        if should_append_wrapper_guidance(&err) {
            let message = format!(
                "{err}
{}",
                wrapper_only_rejection_guidance()
            );
            Box::<dyn std::error::Error>::from(std::io::Error::new(
                std::io::ErrorKind::InvalidInput,
                message,
            ))
        } else {
            Box::<dyn std::error::Error>::from(err)
        }
    })?;
    for warning in imported.warnings() {
        eprintln!("warning: {}", warning.message());
    }
    if let Err(err) = ensure_persistable_run_has_requests(imported.run()) {
        let message = format!("{err}\n{}", wrapper_only_rejection_guidance());
        return Err(std::io::Error::new(std::io::ErrorKind::InvalidInput, message).into());
    }
    create_output_parent_dir(output.as_path())?;
    LocalJsonSink::new(output).write(imported.run())?;
    Ok(())
}

fn should_append_wrapper_guidance(err: &tailtriage_tracing::ImportError) -> bool {
    matches!(
        err,
        tailtriage_tracing::ImportError::ExpectedTailtriageWrapper { .. }
    )
}

fn wrapper_only_rejection_guidance() -> &'static str {
    "stable import expects wrapper JSONL records shaped like {\"format\":\"tailtriage.tracing-span.v1\",\"span\":{...}}. Ordinary tracing_subscriber::fmt().json() logs are unsupported. Pre-stable/internal JSONL must be regenerated with the current writer or converted externally before import."
}

fn main() {
    if let Err(err) = run() {
        eprintln!("{err}");
        std::process::exit(1);
    }
}
