use std::{
    fs,
    path::{Path, PathBuf},
};

use clap::{Parser, ValueEnum};
use tailtriage_analyzer::{
    analyze_option_descriptors, render_json_pretty, render_text, try_analyze_run, AnalyzeOptions,
};
use tailtriage_cli::artifact::load_run_artifact;

#[derive(Debug, Parser)]
#[command(name = "tailtriage")]
#[command(about = "Analyze tailtriage run artifacts", version)]
struct Cli {
    #[command(subcommand)]
    command: Command,
}

#[derive(Debug, clap::Subcommand)]
enum Command {
    /// Analyze one tailtriage run JSON artifact.
    Analyze {
        /// Path to a run JSON file generated by tailtriage-core.
        #[arg(
            value_name = "RUN_JSON",
            required_unless_present = "help_analyzer_options"
        )]
        run_json: Option<PathBuf>,
        /// Output format for the diagnosis report.
        #[arg(long, value_enum, default_value_t = OutputFormat::Text)]
        format: OutputFormat,
        /// Path to analyzer TOML config (`[analyzer]` table with `schema_version`).
        #[arg(long, value_name = "TOML")]
        analyzer_config: Option<PathBuf>,
        /// Analyzer override in PATH=VALUE form. Repeatable; later entries win.
        #[arg(long = "analyzer-set", value_name = "PATH=VALUE")]
        analyzer_set: Vec<String>,
        /// Print analyzer option paths/defaults/types and exit.
        #[arg(long)]
        help_analyzer_options: bool,
    },
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, ValueEnum)]
enum OutputFormat {
    Text,
    Json,
}

fn main() -> Result<(), Box<dyn std::error::Error>> {
    let cli = Cli::parse();

    match cli.command {
        Command::Analyze {
            run_json,
            format,
            analyzer_config,
            analyzer_set,
            help_analyzer_options,
        } => {
            if help_analyzer_options {
                print_analyzer_option_help();
                return Ok(());
            }

            let run_json = run_json.ok_or("missing required argument RUN_JSON")?;
            let loaded = load_run_artifact(&run_json)?;
            for warning in &loaded.warnings {
                eprintln!("warning: {warning}");
            }

            let options = build_analyze_options(analyzer_config.as_deref(), &analyzer_set)?;
            let report = try_analyze_run(&loaded.run, options)?;

            match format {
                OutputFormat::Text => {
                    println!("{}", render_text(&report));
                }
                OutputFormat::Json => {
                    println!("{}", render_json_pretty(&report)?);
                }
            }
        }
    }

    Ok(())
}

fn build_analyze_options(
    analyzer_config: Option<&Path>,
    overrides: &[String],
) -> Result<AnalyzeOptions, Box<dyn std::error::Error>> {
    let mut options = AnalyzeOptions::default();

    if let Some(path) = analyzer_config {
        let contents = fs::read_to_string(path)
            .map_err(|err| format!("failed to read analyzer config '{}': {err}", path.display()))?;
        options = options.merge_toml_str(&contents)?;
    }

    options.apply_overrides(overrides)?;
    Ok(options)
}

fn print_analyzer_option_help() {
    println!("Analyzer options (use with --analyzer-set PATH=VALUE):");
    for descriptor in analyze_option_descriptors() {
        println!("- path: {}", descriptor.path);
        println!("  default: {}", descriptor.default_value);
        println!("  value_type: {}", descriptor.value_type);
        println!("  affects: {}", descriptor.affects);
        println!("  description: {}", descriptor.description);
        if let Some(increasing) = descriptor.increasing {
            println!("  increasing: {increasing}");
        }
        if let Some(decreasing) = descriptor.decreasing {
            println!("  decreasing: {decreasing}");
        }
    }
}

#[cfg(test)]
mod tests {
    use super::build_analyze_options;

    #[test]
    fn default_analyze_options_match_defaults() {
        let built = build_analyze_options(None, &[]).expect("default options should build");
        assert_eq!(built, tailtriage_analyzer::AnalyzeOptions::default());
    }

    #[test]
    fn analyzer_set_override_applies() {
        let built = build_analyze_options(None, &["queueing.trigger_permille=400".to_string()])
            .expect("override should apply");
        assert_eq!(built.queueing.trigger_permille, 400);
    }

    #[test]
    fn repeated_analyzer_set_last_wins() {
        let built = build_analyze_options(
            None,
            &[
                "queueing.trigger_permille=350".to_string(),
                "queueing.trigger_permille=425".to_string(),
            ],
        )
        .expect("overrides should apply");
        assert_eq!(built.queueing.trigger_permille, 425);
    }

    #[test]
    fn invalid_override_path_surfaces_suggestion() {
        let err = build_analyze_options(None, &["queuing.trigger_permille=400".to_string()])
            .expect_err("invalid path should error");
        let msg = err.to_string();
        assert!(msg.contains("did you mean 'queueing.trigger_permille'"));
    }

    #[test]
    fn invalid_override_type_surfaces_expected_type() {
        let err = build_analyze_options(None, &["queueing.trigger_permille=abc".to_string()])
            .expect_err("invalid type should error");
        let msg = err.to_string();
        assert!(msg.contains("expected base-10 unsigned integer (u64)"));
    }

    #[test]
    fn analyzer_toml_applies_before_overrides() {
        let dir = tempfile::tempdir().expect("tempdir should build");
        let path = dir.path().join("analyzer.toml");
        std::fs::write(
            &path,
            "[analyzer]\nschema_version=1\n[analyzer.queueing]\ntrigger_permille=410\n",
        )
        .expect("toml should write");

        let built =
            build_analyze_options(Some(&path), &["queueing.trigger_permille=460".to_string()])
                .expect("toml+override should apply");
        assert_eq!(built.queueing.trigger_permille, 460);
    }

    #[test]
    fn analyzer_toml_parse_errors_use_analyzer_config_error_display() {
        let dir = tempfile::tempdir().expect("tempdir should build");
        let path = dir.path().join("broken.toml");
        std::fs::write(&path, "[analyzer]\nschema_version=1\nqueueing=true\n")
            .expect("broken toml should write");

        let err = build_analyze_options(Some(&path), &[]).expect_err("invalid toml should error");
        let msg = err.to_string();
        assert!(msg.starts_with("invalid toml:"), "actual: {msg}");
    }

    #[test]
    fn analyzer_toml_read_error_includes_path() {
        let path = std::path::PathBuf::from("/definitely/not/here/analyzer.toml");
        let err = build_analyze_options(Some(&path), &[]).expect_err("missing file should error");
        let msg = err.to_string();
        assert!(msg.contains("failed to read analyzer config '/definitely/not/here/analyzer.toml'"));
    }
}
