use std::path::{Path, PathBuf};

use clap::{Parser, ValueEnum};
use tailtriage_analyzer::{
    analyze_option_descriptors, render_json_pretty, render_text, try_analyze_run, AnalyzeOptions,
};
use tailtriage_cli::artifact::load_run_artifact;

#[derive(Debug, Parser)]
#[command(name = "tailtriage")]
#[command(about = "Analyze tailtriage run artifacts", version)]
struct Cli {
    #[command(subcommand)]
    command: Command,
}

#[derive(Debug, clap::Subcommand)]
enum Command {
    /// Analyze one tailtriage run JSON artifact.
    Analyze {
        /// Path to a run JSON file generated by tailtriage-core.
        #[arg(value_name = "RUN_JSON")]
        run_json: Option<PathBuf>,
        /// Output format for the diagnosis report.
        #[arg(long, value_enum, default_value_t = OutputFormat::Text)]
        format: OutputFormat,
        /// Path to analyzer TOML configuration. Merged over built-in defaults.
        #[arg(long, value_name = "TOML")]
        analyzer_config: Option<PathBuf>,
        /// Analyzer override in PATH=VALUE form. Repeatable; later values win.
        #[arg(long = "analyzer-set", value_name = "PATH=VALUE")]
        analyzer_set: Vec<String>,
        /// Print analyzer option help and exit successfully.
        #[arg(long = "help-analyzer-options")]
        help_analyzer_options: bool,
    },
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, ValueEnum)]
enum OutputFormat {
    Text,
    Json,
}

fn main() -> Result<(), Box<dyn std::error::Error>> {
    let cli = Cli::parse();

    match cli.command {
        Command::Analyze {
            run_json,
            format,
            analyzer_config,
            analyzer_set,
            help_analyzer_options,
        } => {
            if help_analyzer_options {
                print_analyzer_option_help();
                return Ok(());
            }

            let run_json = run_json.ok_or_else(|| {
                clap::Error::raw(
                    clap::error::ErrorKind::MissingRequiredArgument,
                    "missing required argument RUN_JSON (unless --help-analyzer-options is used)",
                )
            })?;

            let loaded = load_run_artifact(&run_json)?;
            for warning in &loaded.warnings {
                eprintln!("warning: {warning}");
            }
            let options = build_analyze_options(analyzer_config.as_deref(), &analyzer_set)?;
            let report = try_analyze_run(&loaded.run, options)?;

            match format {
                OutputFormat::Text => {
                    println!("{}", render_text(&report));
                }
                OutputFormat::Json => {
                    println!("{}", render_json_pretty(&report)?);
                }
            }
        }
    }

    Ok(())
}

fn build_analyze_options(
    analyzer_config: Option<&Path>,
    analyzer_set: &[String],
) -> Result<AnalyzeOptions, Box<dyn std::error::Error>> {
    let mut options = AnalyzeOptions::default();

    if let Some(path) = analyzer_config {
        let config = std::fs::read_to_string(path).map_err(|error| {
            format!(
                "failed reading analyzer config '{}': {error}",
                path.display()
            )
        })?;
        options = options.merge_toml_str(&config)?;
    }

    options.apply_overrides(analyzer_set.iter().map(String::as_str))?;
    Ok(options)
}

fn print_analyzer_option_help() {
    println!("Analyzer option paths (use with --analyzer-set PATH=VALUE or --analyzer-config):\n");
    for descriptor in analyze_option_descriptors() {
        println!("- {}", descriptor.path);
        println!("  default: {}", descriptor.default_value);
        println!("  value type: {}", descriptor.value_type);
        println!("  affects: {}", descriptor.affects);
        println!("  description: {}", descriptor.description);
        if let Some(increasing) = descriptor.increasing {
            println!("  increasing: {increasing}");
        }
        if let Some(decreasing) = descriptor.decreasing {
            println!("  decreasing: {decreasing}");
        }
        println!();
    }
}
