use std::time::Instant;

use crate::collector::duration_to_us;
use crate::{unix_time_ms, InflightGuard, QueueTimer, StageTimer, Tailtriage};

/// Reusable per-request context for fractured-code instrumentation.
#[derive(Debug)]
pub struct RequestContext<'a> {
    tailtriage: &'a Tailtriage,
    request_id: String,
    route: String,
    kind: Option<String>,
    started_at_unix_ms: u64,
    started: Instant,
}

impl<'a> RequestContext<'a> {
    pub(crate) fn new(tailtriage: &'a Tailtriage, request_id: String, route: String) -> Self {
        Self {
            tailtriage,
            request_id,
            route,
            kind: None,
            started_at_unix_ms: unix_time_ms(),
            started: Instant::now(),
        }
    }

    /// Annotates this request with an optional semantic kind.
    #[must_use]
    pub fn with_kind(mut self, kind: impl Into<String>) -> Self {
        self.kind = Some(kind.into());
        self
    }

    /// Returns the request correlation ID generated by tailtriage.
    #[must_use]
    pub fn request_id(&self) -> &str {
        &self.request_id
    }

    /// Instruments one queue wait segment for this request.
    #[must_use]
    pub fn queue(&self, queue: impl Into<String>) -> QueueTimer<'_> {
        self.tailtriage.queue(self.request_id.clone(), queue)
    }

    /// Instruments one stage segment for this request.
    #[must_use]
    pub fn stage(&self, stage: impl Into<String>) -> StageTimer<'_> {
        self.tailtriage.stage(self.request_id.clone(), stage)
    }

    /// Increments/decrements an in-flight gauge while a guard is alive.
    #[must_use]
    pub fn inflight(&self, gauge: impl Into<String>) -> InflightGuard<'_> {
        self.tailtriage.inflight(gauge)
    }

    /// Completes this request context and records request latency/outcome.
    pub fn complete(&self, outcome: impl Into<String>) {
        let finished_at_unix_ms = unix_time_ms();
        self.tailtriage.record_request_fields(
            self.request_id.clone(),
            self.route.clone(),
            self.kind.clone(),
            (self.started_at_unix_ms, finished_at_unix_ms),
            duration_to_us(self.started.elapsed()),
            outcome,
        );
    }
}
