#![allow(clippy::too_many_lines)]

/// Metadata about a semantic analyzer option.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct AnalyzeOptionDescriptor {
    pub path: &'static str,
    pub default_value: &'static str,
    pub value_type: &'static str,
    pub affects: &'static str,
    pub description: &'static str,
    pub increasing: Option<&'static str>,
    pub decreasing: Option<&'static str>,
}

#[must_use]
pub fn analyze_option_descriptors() -> Vec<AnalyzeOptionDescriptor> {
    vec![
        d(
            "queueing.trigger_permille",
            "300",
            "u64",
            "queue suspect triggering",
            "Minimum p95 queue-share permille before queueing is considered a strong lead.",
            Some("Makes queueing suspect trigger less often."),
            Some("Makes queueing suspect trigger more often."),
        ),
        d(
            "blocking.min_nonzero_samples_for_signal",
            "2",
            "usize",
            "blocking suspect triggering",
            "Minimum non-zero blocking samples needed before blocking pressure can be signaled.",
            Some("Requires more blocking evidence before signaling."),
            Some("Allows signaling with less blocking evidence."),
        ),
        d(
            "blocking.strong_p95_threshold",
            "12",
            "u64",
            "blocking suspect ranking",
            "P95 blocking queue depth threshold for stronger blocking pressure evidence.",
            Some("Makes strong blocking evidence harder to reach."),
            Some("Makes strong blocking evidence easier to reach."),
        ),
        d(
            "blocking.strong_peak_threshold",
            "20",
            "u64",
            "blocking suspect ranking",
            "Peak blocking queue depth threshold for stronger blocking pressure evidence.",
            Some("Makes strong blocking evidence harder to reach."),
            Some("Makes strong blocking evidence easier to reach."),
        ),
        d(
            "blocking.strong_nonzero_share_permille",
            "700",
            "u64",
            "blocking suspect ranking",
            "Minimum non-zero share permille for stronger blocking pressure evidence.",
            Some("Makes strong blocking evidence harder to reach."),
            Some("Makes strong blocking evidence easier to reach."),
        ),
        d(
            "blocking.strong_min_samples",
            "30",
            "usize",
            "blocking suspect ranking",
            "Minimum blocking sample count used for stronger blocking pressure evidence.",
            Some("Needs larger sample sizes for strong blocking confidence."),
            Some("Allows strong blocking confidence with smaller samples."),
        ),
        d(
            "executor.min_global_queue_p95_for_signal",
            "1",
            "u64",
            "executor suspect triggering",
            "Minimum runtime global queue p95 to consider executor pressure signal.",
            Some("Makes executor-pressure signal less sensitive."),
            Some("Makes executor-pressure signal more sensitive."),
        ),
        d(
            "downstream.min_stage_samples",
            "3",
            "usize",
            "downstream suspect triggering",
            "Minimum stage sample count required before downstream stage dominance is considered.",
            Some("Requires more stage evidence before downstream suspect appears."),
            Some("Allows downstream suspect with fewer stage samples."),
        ),
        d(
            "downstream.blocking_correlated_stage_patterns",
            "[\"spawn_blocking\", \"blocking_path\", \"blocking\"]",
            "Vec<String>",
            "blocking/downstream tie-break context",
            "Stage name patterns used to correlate downstream stages with blocking-heavy paths.",
            Some("Adds stricter pattern requirements if you narrow patterns."),
            Some("Adds broader correlation if you widen patterns."),
        ),
        d(
            "downstream.blocking_correlation_score_margin",
            "2",
            "u8",
            "blocking/downstream tie-break behavior",
            "Score margin used when correlating downstream stage dominance with blocking patterns.",
            Some("Needs a larger margin before correlation affects ranking."),
            Some("Allows smaller margin to affect ranking."),
        ),
        d(
            "confidence.medium_score_threshold",
            "65",
            "u8",
            "confidence bucket assignment",
            "Minimum suspect score considered medium confidence.",
            Some("Raises bar for medium confidence."),
            Some("Lowers bar for medium confidence."),
        ),
        d(
            "confidence.high_score_threshold",
            "85",
            "u8",
            "confidence bucket assignment",
            "Minimum suspect score considered high confidence.",
            Some("Raises bar for high confidence."),
            Some("Lowers bar for high confidence."),
        ),
        d(
            "confidence.ambiguity_min_score",
            "60",
            "u8",
            "ambiguity signaling",
            "Minimum score at which ambiguity checks are considered meaningful.",
            Some("Requires stronger scores before ambiguity handling applies."),
            Some("Allows ambiguity handling at lower scores."),
        ),
        d(
            "confidence.ambiguity_score_gap",
            "4",
            "u8",
            "ambiguity signaling",
            "Maximum top-score gap treated as ambiguous between close suspects.",
            Some("Reduces ambiguous outcomes to closer ties only."),
            Some("Increases ambiguous outcomes across wider ties."),
        ),
        d(
            "evidence.low_completed_request_threshold",
            "20",
            "usize",
            "evidence quality classification",
            "Completed-request threshold under which evidence quality is considered weaker.",
            Some("Keeps stronger evidence classification harder to reach."),
            Some("Allows stronger evidence classification sooner."),
        ),
        d(
            "route.min_request_count",
            "3",
            "usize",
            "route breakdown emission",
            "Minimum per-route request count before route breakdowns are included.",
            Some("Suppresses small-route breakdowns more often."),
            Some("Emits small-route breakdowns more often."),
        ),
        d(
            "route.breakdown_limit",
            "10",
            "usize",
            "route breakdown emission",
            "Maximum number of route breakdown rows emitted in a report.",
            Some("Limits route breakdown output more aggressively."),
            Some("Allows more route breakdown rows."),
        ),
        d(
            "route.emit_on_divergent_suspects",
            "true",
            "bool",
            "route warning emission",
            "Whether to emit a route-divergence warning when route suspects disagree.",
            Some("Enables more route-divergence warning output."),
            Some("Suppresses route-divergence warning output."),
        ),
        d(
            "route.slowest_to_fastest_p95_ratio_numerator",
            "3",
            "u64",
            "route divergence thresholds",
            "Numerator for slowest/fastest route p95 ratio threshold.",
            Some("Raises threshold if denominator unchanged."),
            Some("Lowers threshold if denominator unchanged."),
        ),
        d(
            "route.slowest_to_fastest_p95_ratio_denominator",
            "2",
            "u64",
            "route divergence thresholds",
            "Denominator for slowest/fastest route p95 ratio threshold.",
            Some("Lowers threshold if numerator unchanged."),
            Some("Raises threshold if numerator unchanged."),
        ),
        d(
            "route.slowest_to_global_p95_ratio_numerator",
            "5",
            "u64",
            "route divergence thresholds",
            "Numerator for slowest-route/global p95 ratio threshold.",
            Some("Raises threshold if denominator unchanged."),
            Some("Lowers threshold if denominator unchanged."),
        ),
        d(
            "route.slowest_to_global_p95_ratio_denominator",
            "4",
            "u64",
            "route divergence thresholds",
            "Denominator for slowest-route/global p95 ratio threshold.",
            Some("Lowers threshold if numerator unchanged."),
            Some("Raises threshold if numerator unchanged."),
        ),
        d(
            "temporal.min_request_count",
            "20",
            "usize",
            "temporal segmentation",
            "Minimum run request count before temporal segment analysis is emitted.",
            Some("Suppresses temporal analysis for more runs."),
            Some("Emits temporal analysis for more runs."),
        ),
        d(
            "temporal.min_segment_request_count",
            "8",
            "usize",
            "temporal segmentation",
            "Minimum request count required per temporal segment.",
            Some("Requires denser segments before temporal output appears."),
            Some("Allows sparser segments in temporal output."),
        ),
        d(
            "temporal.share_shift_permille",
            "200",
            "u64",
            "temporal suspect-shift detection",
            "Minimum queue/service share movement permille before shift is considered meaningful.",
            Some("Requires larger share movement for shift signaling."),
            Some("Allows smaller share movement for shift signaling."),
        ),
        d(
            "temporal.p95_shift_ratio_numerator",
            "3",
            "u64",
            "temporal suspect-shift detection",
            "Numerator for temporal p95 shift ratio threshold.",
            Some("Raises shift threshold if denominator unchanged."),
            Some("Lowers shift threshold if denominator unchanged."),
        ),
        d(
            "temporal.p95_shift_ratio_denominator",
            "2",
            "u64",
            "temporal suspect-shift detection",
            "Denominator for temporal p95 shift ratio threshold.",
            Some("Lowers shift threshold if numerator unchanged."),
            Some("Raises shift threshold if numerator unchanged."),
        ),
        d(
            "temporal.emit_on_suspect_shift",
            "true",
            "bool",
            "temporal warning emission",
            "Whether to emit temporal segment output when suspect shifts are detected.",
            Some("Enables temporal shift output emission."),
            Some("Suppresses temporal shift output emission."),
        ),
        d(
            "temporal.suppress_runtime_sparse_suspect_shift_without_supporting_movement",
            "true",
            "bool",
            "temporal suspect-shift filtering",
            "Suppresses runtime-sparse suspect-shift output without supporting movement evidence.",
            Some("Suppresses more sparse runtime-only shifts."),
            Some("Allows more sparse runtime-only shifts."),
        ),
    ]
}

fn d(
    path: &'static str,
    default_value: &'static str,
    value_type: &'static str,
    affects: &'static str,
    description: &'static str,
    increasing: Option<&'static str>,
    decreasing: Option<&'static str>,
) -> AnalyzeOptionDescriptor {
    AnalyzeOptionDescriptor {
        path,
        default_value,
        value_type,
        affects,
        description,
        increasing,
        decreasing,
    }
}
